### ISSUE TITLE
Corrupted player join, advancement, and death message on server (Fabric 1.20.1,  More Shield Variants version 1.2.0

### ISSUE THREAD

**Issue by Gl0wstone** [pnk2u/More-Shield-Variants#6] opened 2024-09-18 16:05 UTC
I have a long mod list on our 1.20.1 Fabric server and noticed we were getting weird console output.  After hours of troubleshooting and removing/adding mods to narrow it down, somehow this mod only (mod version 1.2.0), when loaded, causes the console to corrupt the readout of things like Death announcements, Advancements and player join/leave announcements.  The in-game player announcements in chat is **fine**, but the console is flawed and for any other mod or process reading the console (like a Discord relay) the result is ugly.

Here's the dedicated server log when More Shield Variants is loaded:

```
[11:38:46] [Netty Server IO #1/INFO]: Receiving client config
**[11:38:46] [Server thread/INFO]: multiplayer.player.joined
[11:38:55] [Server thread/INFO]: chat.type.admin
[11:38:58] [Server thread/INFO]: death.attack.genericKill
[11:38:58] [Server thread/INFO]: chat.type.admin
[11:38:58] [Server thread/INFO]: chat.type.admin
[11:42:09] [Server thread/INFO]: chat.type.advancement.task
[11:42:09] [Server thread/INFO]: chat.type.admin
[11:42:18] [Server thread/INFO]: chat.type.advancement.task
[11:42:18] [Server thread/INFO]: chat.type.admin**
[11:53:40] [Netty Server IO #1/INFO]: Receiving client config
**[11:53:40] [Server thread/INFO]: multiplayer.player.joined**
[11:53:47] [Worker-Main-5/ERROR]: Hanging entity at invalid position: class_2338{x=-169, y=-51, z=-80}
[11:53:52] [Server thread/INFO]: death.attack.genericKill
**[11:53:52] [Server thread/INFO]: chat.type.admin
[11:53:52] [Server thread/INFO]: chat.type.admin**
[11:53:52] [Worker-Main-6/ERROR]: Hanging entity at invalid position: class_2338{x=-169, y=-51, z=-77}
**[11:54:00] [Server thread/INFO]: multiplayer.player.left**
```

Examples of correct console readout once More Shield Variants (and only More Shield Variants) is removed, all other variables constant
```
[11:33:40] [Server thread/INFO]: Player123 joined the game
[11:33:49] [Server thread/INFO]: Player123  was killed
[11:34:10] [Server thread/INFO]: Player123  has made the advancement [Acquire Hardware]
[11:34:17] [Server thread/INFO]: Player123  left the game
```

I don't know what's happening or what else MSV (or Quad) may be interacting with.  But here's the complete mod list present to recreate this.

```
[main/INFO]: Loading 246 mods:
	- advancementframes 1.20-2.2.7
	- afkplus 1.4.9
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   |-- fabric-permissions-api-v0 0.3-SNAPSHOT
	   \-- placeholder-api 2.1.3+1.20.1
	- allaybottle 1.1.2
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- areas 6.0
	- bakery 1.1.15
	- basicweapons 1.2.3+1.20.1
	- bedspreads 6.2.0+1.20.1
	- beekeeperhut 2.0.1
	- betterarcheology 1.2.1-1.20.1
	- bettercombat 1.8.6+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.4
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.5
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- bettertridents 8.0.1
	- betterwitchhuts 1.20-Fabric-3.0.3
	- brewery 1.1.9
	- carryon 2.1.2.7
	- chalk 2.2.4
	   |-- com_github_mclegoman_releasetypeutils 2.1.0
	   \-- fabric-simplelibs 2.0.0
	- charm 6.0.21
	   |-- charmony 6.15.1
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- charmony_api 6.7.0
	- chimes 2.0.1
	- chunky 1.3.146
	- chunkyborder 1.1.53
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- collective 7.84
	- combatroll 1.3.3+1.20.1
	- connectiblechains 2.2.1+1.20.1
	- coroutil 1.20.1-1.3.7
	- craterlib 2.1.0
	- creeperoverhaul 3.0.2
	   \-- resourcefullib 2.1.20
	        |-- com_teamresourceful_bytecodecs 1.0.2
	        \-- com_teamresourceful_yabn 1.0.3
	- ctov 3.4.7
	- dailydad_server 1.4.1
	- dawn 5.0.0
	   |-- terraform-shapes-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- deathcounter 1.4.0
	- deathknell 10.0.4
	- dedicatedlanpinger 1.1
	- diagonalfences 8.1.4
	   \-- diagonalblocks 8.0.5
	- diagonalwalls 8.0.3
	   \-- diagonalblocks 8.0.5
	- diagonalwindows 8.1.4
	   \-- diagonalblocks 8.0.5
	- doapi 1.2.15
	   \-- terraform-wood-api-v1 7.0.1
	- dramaticdoors 1.20.1-3.2.3
	- dummmmmmy 1.20-2.0.0
	- dungeonnowloading 1.5
	- early_game_overhaul 1.0.3
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- emotecraft 2.2.7-b.build.50
	   |-- bendy-lib 4.0.0
	   \-- player-animator 1.0.2-rc1+1.20
	- endermanoverhaul 1.0.4
	- exposure 1.7.6
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- farmersdelight 1.20.1-2.1.6+refabricated
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    |-- porting_lib_entity 2.3.4+1.20.1
	   |    |-- porting_lib_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_fluids 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_transfer 2.3.4+1.20.1
	   |    |-- porting_lib_utility 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_config 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_tool_actions 2.3.4+1.20.1
	        \-- porting_lib_core 2.3.4+1.20.1
	- ferritecore 6.0.1
	- flowerymooblooms 2.0.2
	- forgeconfigapiport 8.0.0
	- framework 0.6.16
	   \-- org_javassist_javassist 3.29.2-GA
	- friendsandfoes 2.0.17
	- furnacerecycle 2.5
	- furniture 1.0.2
	- geckolib 4.4.9
	   \-- com_eliotlash_mclib_mclib 20
	- guardvillagers 2.0.9-1.20.1
	   \-- midnightlib 1.4.1
	- hangglider 8.0.1
	- herbalbrews 1.0.8.1
	- herdspanic 1.1.0
	- highspeed-rail 0.4.0+1.20.1
	- hopobetterunderwaterruins 1.1.4
	- horsebuff 2.1.2
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b27
	- ichunutil 1.0.0
	- illagerinvasion 8.0.5
	   \-- extensibleenums 7.0.1
	- immersive_aircraft 1.1.0+1.20.1
	   \-- org_mariuszgromada_math_mathparser_org-mxparser 5.2.1
	- immersive_melodies 0.3.0+1.20.1
	- immersive_paintings 0.6.7+1.20.1
	- immersive_weathering 1.20.1-2.0.2
	- incendium 5.3.5
	- interactic 0.2.0+1.20
	- inventory_sort 1.2.4+1.20
	- jade 11.11.0+fabric
	- java 17
	- kaffees_dual_ride 1.1.0
	- kiwi 11.8.24+fabric
	- lavender 0.1.9+1.20
	   |-- lavender-md 0.1.1+1.20
	   \-- lavender-md-owo-ui 0.1.1+1.20
	- leafmealone 1.0.1
	- lenientdeath 1.2.5+1.20.1
	   |-- jackfredlib-base 1.4.0+1.20.1
	   |-- jackfredlib-colour 1.1.0+1.20.1
	   |-- jackfredlib-config 0.2.3+1.20.1
	   |    |-- blue_endless_jankson 1.2.3
	   |    |-- commons-io_commons-io 2.15.1
	   |    \-- jackfredlib-base 1.4.0+1.20.1
	   |-- jackfredlib-lying 0.5.6+1.20.1
	   \-- server_translations_api 2.0.0+1.20
	        \-- packet_tweaker 0.4.0+1.19.4
	- lithium 0.11.2
	- lithostitched 1.1.8
	- lolmsv 1.2.0
	- meadow 1.3.19
	   \-- mixinsquared 0.1.2-beta.5
	- mes 1.3.1-1.20-fabric
	- mighty_mail 1.0.14
	- minecraft 1.20.1
	- mobs_attempt_parkour 0.5.2-1.20
	   \-- maelstrom_library 1.6.1-1.20
	- moonlight 1.20-2.12.20
	- morebannerfeatures 1.2.0
	- moremobs 1.5.2+mod
	- moremobvariants 1.3.1
	- mr_allay_upgrades 2.0
	- mr_bft 2.0.0
	- mr_cheaper_clocks 2.1
	- mr_cheaper_compasses 2.1
	- mr_cheaper_maps 1.0
	- mr_kawatts_cheaperlanterns 1.0
	- mr_remove_terralithintromessage 1.1
	- mss 1.1.2-1.20-fabric
	- mutantmonsters 8.0.7
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   \-- extensibleenums 7.0.1
	- mvs 4.1.2-1.20-fabric
	- mysticaloaktree 1.20-1.11
	- nametagtweaks 3.8
	- naturalist 4.0.3
	- nethersdelight 1.20.1-4.1.1
	- nethervinery 1.2.14
	- nullscape 1.2.7
	- owo 0.11.2+1.20
	- puzzleslib 8.1.23
	   \-- puzzlesaccessapi 8.0.7
	- quad 1.3.0-beta.3
	- regrowth 83.31.1
	- resourcefulconfig 2.1.2
	- sdlink 3.1.6
	- sparsestructures 2.2.0
	- supermartijn642configlib 1.1.8+a
	- sushi_bar 0.2.2+1.20
	   \-- com_moulberry_mixinconstraints 1.0.1
	- tectonic 2.4.1b
	- terralith 2.5.4
	- vinery 1.4.28
	- visualizerbookshelf 2.0
	- wilderwild 2.4.6-mc1.20.1
	   |-- frozenlib 1.8-mc1.20.1
	   \-- reach-entity-attributes 2.4.0
	- yungsapi 1.20-Fabric-4.0.5
```

**Comment by pnk2u** [comment] 2024-09-18 23:22
Thanks for reporting this. I was able to reproduce the issue and found a way to circumvent the underlying cause. It should be fixed in version 1.2.2. Let me know if that fixes the problem on your side as well to confirm.

**Comment by Gl0wstone** [comment] 2024-09-23 17:20
I was able to test the new release today (MSV version 1.2.2) and unfortunately getting the same results in the console.

```
[13:08:22] [Netty Server IO #1/INFO]: Receiving client config
[13:08:22] [Server thread/INFO]: multiplayer.player.joined
[13:09:10] [Server thread/INFO]: death.attack.genericKill
[13:09:10] [Server thread/INFO]: chat.type.admin
[13:09:10] [Server thread/INFO]: chat.type.admin
```

The only change made was installing MSV and Quad.  (happens with or without Quad installed on server).

<img width="394" alt="Screenshot 2024-09-23 at 1 19 44 PM" src="https://github.com/user-attachments/assets/2c13e145-8f6c-499b-ba76-c1d1a9074ca3">

**Comment by pnk2u** [comment] 2024-09-23 18:15
Unfortunately I'm unable to reproduce it any more on my end. Both with Quad and without it.
The only thing I could see being the reason if maybe there is still an older version of MSV installed alongside 1.2.2.
Could you please provide a more complete version of the logs so I can further investigate?

**Comment by Gl0wstone** [comment] 2024-09-23 19:47
I checked and had a hard time confirming the name actually. the mod file is named clearly labeled but fabric loads it as lolmsv, I believe.  Anyway, here is the server log from when the server loads up with MSV+Quad if it helps.

There was no old version of MSV leftover in my testing today.

https://mclo.gs/rrXpRKF

**Comment by pnk2u** [comment] 2024-09-23 21:05
Yes, lolmsv is correct.
So, the only reason I know of this could happen for, is having language files (naming Items and such) on the server-side as it doesn't like that. Since I fixed that part, it doesn't occur on my side any more, but to find your issue I think a bit more trial and error is involved. If you would be so kind, please contact me on Discord with the same username as here and then I can send you a few potential fixes directly to get this sorted. (:

**Comment by pnk2u** [comment] 2024-10-15 10:26
As there has been no response, I will close this issue for now.

**Closed as completed by pnk2u** 2024-10-15 10:26 UTC
